A Rahul (20BRS1102)

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
cd /content/drive/MyDrive/20BRS1102 Deep Learning Lab/Lab 02 - 15 12 22

/content/drive/MyDrive/20BRS1102 Deep Learning Lab/Lab 02 - 15 12 22


In [3]:
import numpy as np
import tensorflow as tf
import cv2

# **Classroom Exercises**

In [4]:
#Scalar data representation

x1 = np.array(12)
print("x1: ", x1)
print("shape of x1: ", x1.shape)
print("dimensions in x1: ", x1.ndim, end="\n\n")

x2 = tf.constant(12, shape=(), dtype=tf.float64)
print("x2: ", x2)
print("shape of x2: ", x2.shape)
print("dimensions in x2: ", x2.ndim, end="\n\n")

x3 = tf.Variable(12, dtype=tf.int64)
print("x3: ", x3)
print("shape of x3: ", x3.shape, end="\n\n")

x1:  12
shape of x1:  ()
dimensions in x1:  0

x2:  tf.Tensor(12.0, shape=(), dtype=float64)
shape of x2:  ()
dimensions in x2:  0

x3:  <tf.Variable 'Variable:0' shape=() dtype=int64, numpy=12>
shape of x3:  ()



In [5]:
#Vector data (1D) representation

v1 = np.array([12, 3, 6, 14, 5])
print("v1: ", v1)
print("shape of v1: ", v1.shape)
print("dimensions in v1: ", v1.ndim, end="\n\n")

v2 = tf.constant([12, 3, 6, 14, 5], dtype=tf.float32)
print("v2: ", v2)
print("shape of v2: ", v2.shape)
print("dimensions in v2: ", v2.ndim, end="\n\n")

v3 = tf.Variable([12, 3, 6, 14, 5], dtype=tf.int32)
print("v3: ", v3)
print("shape of v3: ", v3.shape, end="\n\n")

v1:  [12  3  6 14  5]
shape of v1:  (5,)
dimensions in v1:  1

v2:  tf.Tensor([12.  3.  6. 14.  5.], shape=(5,), dtype=float32)
shape of v2:  (5,)
dimensions in v2:  1

v3:  <tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([12,  3,  6, 14,  5], dtype=int32)>
shape of v3:  (5,)



In [6]:
#Matrix data (2D) representation

m1 = np.array([[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]])
print("m1: ", m1)
print("shape of m1: ", m1.shape)
print("dimensions in m1: ", m1.ndim, end="\n\n")

m2 = tf.constant([[5, 78, 2, 34, 0],
                  [6, 79, 3, 35, 1],
                  [7, 80, 4, 36, 2]], dtype=tf.float32)
print("m2: ", m2)
print("shape of m2: ", m2.shape)
print("dimensions in m2: ", m2.ndim, end="\n\n")

m3 = tf.Variable([[5, 78, 2, 34, 0],
                  [6, 79, 3, 35, 1],
                  [7, 80, 4, 36, 2]], dtype=tf.int32)
print("m3: ", m3)
print("shape of m3: ", m3.shape, end="\n\n")

m1:  [[ 5 78  2 34  0]
 [ 6 79  3 35  1]
 [ 7 80  4 36  2]]
shape of m1:  (3, 5)
dimensions in m1:  2

m2:  tf.Tensor(
[[ 5. 78.  2. 34.  0.]
 [ 6. 79.  3. 35.  1.]
 [ 7. 80.  4. 36.  2.]], shape=(3, 5), dtype=float32)
shape of m2:  (3, 5)
dimensions in m2:  2

m3:  <tf.Variable 'Variable:0' shape=(3, 5) dtype=int32, numpy=
array([[ 5, 78,  2, 34,  0],
       [ 6, 79,  3, 35,  1],
       [ 7, 80,  4, 36,  2]], dtype=int32)>
shape of m3:  (3, 5)



In [7]:
#Representation of 3D and higher dimensional tensors

t1 = np.array([
               [[5, 78, 2, 34, 0],
                [6, 79, 3, 35, 1],
                [7, 80, 4, 36, 2]],

               [[5, 78, 2, 34, 0],
                [6, 79, 3, 35, 1],
                [7, 80, 4, 36, 2]],

               [[5, 78, 2, 34, 0],
                [6, 79, 3, 25, 1],
                [7, 80, 4, 36, 2]]
            ])
print("t1: ", t1)
print("shape of t1: ", t1.shape)
print("dimensions in t1: ", t1.ndim, end="\n\n")

t2 = tf.constant([
               [[5, 78, 2, 34, 0],
                [6, 79, 3, 35, 1],
                [7, 80, 4, 36, 2]],

               [[5, 78, 2, 34, 0],
                [6, 79, 3, 35, 1],
                [7, 80, 4, 36, 2]],

               [[5, 78, 2, 34, 0],
                [6, 79, 3, 25, 1],
                [7, 80, 4, 36, 2]]
            ])
print("t2: ", t2)
print("shape of t2: ", t2.shape)
print("dimensions in t2: ", t2.ndim, end="\n\n")

t3 = tf.Variable([
               [[5, 78, 2, 34, 0],
                [6, 79, 3, 35, 1],
                [7, 80, 4, 36, 2]],

               [[5, 78, 2, 34, 0],
                [6, 79, 3, 35, 1],
                [7, 80, 4, 36, 2]],

               [[5, 78, 2, 34, 0],
                [6, 79, 3, 25, 1],
                [7, 80, 4, 36, 2]]
            ])
print("t3: ", t3)
print("shape of t3: ", t3.shape, end="\n\n")

t1:  [[[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]

 [[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]

 [[ 5 78  2 34  0]
  [ 6 79  3 25  1]
  [ 7 80  4 36  2]]]
shape of t1:  (3, 3, 5)
dimensions in t1:  3

t2:  tf.Tensor(
[[[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]

 [[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]

 [[ 5 78  2 34  0]
  [ 6 79  3 25  1]
  [ 7 80  4 36  2]]], shape=(3, 3, 5), dtype=int32)
shape of t2:  (3, 3, 5)
dimensions in t2:  3

t3:  <tf.Variable 'Variable:0' shape=(3, 3, 5) dtype=int32, numpy=
array([[[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]],

       [[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]],

       [[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 25,  1],
        [ 7, 80,  4, 36,  2]]], dtype=int32)>
shape of t3:  (3, 3, 5)



In [8]:
#print(tf.keras.activations.relu(m1.T.dot(m2)))
def naive_relu(x):
    assert len(x.shape) == 2
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] = max(x[i, j], 0)
    return x

print("Output of the custom relu function: ", naive_relu(m1), end="\n\n")

print("Output of the tensorflow relu function: ", tf.keras.activations.relu(m1), end="\n\n")




Output of the custom relu function:  [[ 5 78  2 34  0]
 [ 6 79  3 35  1]
 [ 7 80  4 36  2]]

Output of the tensorflow relu function:  tf.Tensor(
[[ 5 78  2 34  0]
 [ 6 79  3 35  1]
 [ 7 80  4 36  2]], shape=(3, 5), dtype=int64)



In [9]:
layer = tf.keras.layers.Dense(512, activation='relu')
print("weights: ", layer.weights)

#tf.keras.activations.relu(np.dot(layer.weights, m1))


weights:  []


In [10]:
def naive_add(x, y):
    assert len(x.shape) == 2
    assert x.shape == y.shape

    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[i, j]
    return x

print(naive_add(m1, m1), end="\n\n")

z = m1 + m1
z = np.maximum(z, 0.)
print(z, end="\n\n")

print(tf.add(m1, m1), end="\n\n")


[[ 10 156   4  68   0]
 [ 12 158   6  70   2]
 [ 14 160   8  72   4]]

[[ 10. 156.   4.  68.   0.]
 [ 12. 158.   6.  70.   2.]
 [ 14. 160.   8.  72.   4.]]

tf.Tensor(
[[ 10 156   4  68   0]
 [ 12 158   6  70   2]
 [ 14 160   8  72   4]], shape=(3, 5), dtype=int64)



In [11]:
def naive_add_matrix_and_vector(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]

    x=x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[j]
    return x

print(naive_add_matrix_and_vector(m1, v1), end="\n\n")

print(m1+v1, end="\n\n")

print(tf.add(m1, v1), end="\n\n")

[[17 81  8 48  5]
 [18 82  9 49  6]
 [19 83 10 50  7]]

[[17 81  8 48  5]
 [18 82  9 49  6]
 [19 83 10 50  7]]

tf.Tensor(
[[17 81  8 48  5]
 [18 82  9 49  6]
 [19 83 10 50  7]], shape=(3, 5), dtype=int64)



# **Declare a 5D tensor and show its dimensions**

In [12]:
x = np.array([[[[[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]]],
              [[[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]]]]])

x.ndim

5

# **Operations on realtime 5D datasets**

**Read the first 10 frames of video 1 from its path  (4 dimensions; length, bredth, color, time)**

In [13]:
cap = cv2.VideoCapture('V1.avi')
s1 = []
n = 0
while(n<10):
  ret, frame = cap.read()
  if ret:
    frame = cv2.resize(frame, (300,300), fx=0, fy=0, interpolation = cv2.INTER_CUBIC)
    s1.append(frame)
    n = n + 1
    if cv2.waitKey(25) & 0xFF == ord('q'):
      break
  else:
    cap.set(cv2.CAP_PROP_POS_FRAMES, 0)
    break

cap.release()
cv2.destroyAllWindows()

**Read the first 10 frames of video 2 from its path (4 dimensions; length, bredth, color, time)**

In [14]:
cap = cv2.VideoCapture('V2.avi')
s2 = []
n = 0
while(n<10):
  ret, frame = cap.read()
  if ret:
    frame = cv2.resize(frame, (300,300), fx=0, fy=0, interpolation = cv2.INTER_CUBIC)
    s2.append(frame)
    n = n + 1
    if cv2.waitKey(25) & 0xFF == ord('q'):
      break
  else:
    cap.set(cv2.CAP_PROP_POS_FRAMES, 0)
    break

cap.release()
cv2.destroyAllWindows()

**Put video 1 and 2 into an array to form a 5D tensor**

In [15]:
vidset1 = np.array([s1,s2])
print(vidset1.ndim)
print(vidset1.shape)

5
(2, 10, 300, 300, 3)


**Read the first 10 frames of video 3 from its path (4 dimensions; length, bredth, color, time)**

In [16]:
cap = cv2.VideoCapture('V3.avi')
s1 = []
n = 0
while(n<10):
  ret, frame = cap.read()
  if ret:
    frame = cv2.resize(frame, (300,300), fx=0, fy=0, interpolation = cv2.INTER_CUBIC)
    s1.append(frame)
    n = n + 1
    if cv2.waitKey(25) & 0xFF == ord('q'):
      break
  else:
    cap.set(cv2.CAP_PROP_POS_FRAMES, 0)
    break

cap.release()
cv2.destroyAllWindows()

**Read the first 10 frames of video 4 from its path (4 dimensions; length, bredth, color, time)**

In [17]:
cap = cv2.VideoCapture('V4.avi')
s2 = []
n = 0
while(n<10):
  ret, frame = cap.read()
  if ret:
    frame = cv2.resize(frame, (300,300), fx=0, fy=0, interpolation = cv2.INTER_CUBIC)
    s2.append(frame)
    n = n + 1
    if cv2.waitKey(25) & 0xFF == ord('q'):
      break
  else:
    cap.set(cv2.CAP_PROP_POS_FRAMES, 0)
    break

cap.release()
cv2.destroyAllWindows()

**Put video 3 and 4 into an array to form a 5D tensor**

In [18]:
vidset2 = np.array([s1,s2])
print(vidset2.ndim)
print(vidset2.shape)

5
(2, 10, 300, 300, 3)


**Define functions to add or subtract the 5D tensors made using videos**

In [19]:
def subtractVideos(x1, x2):
  assert x1.ndim == 5
  assert x2.ndim == 5
  for i1 in range(x1.shape[0]):
    for i2 in range(x1.shape[1]):
      for i3 in range(x1.shape[2]):
        for i4 in range(x1.shape[3]):
          for i5 in range(x1.shape[4]):
            if x1[i1][i2][i3][i4][i5] > x2[i1][i2][i3][i4][i5]:
              x1[i1][i2][i3][i4][i5] -= x2[i1][i2][i3][i4][i5]
  
  return x1

In [20]:
def addVideos(x1, x2):
  assert x1.ndim == 5
  assert x2.ndim == 5
  for i1 in range(x1.shape[0]):
    for i2 in range(x1.shape[1]):
      for i3 in range(x1.shape[2]):
        for i4 in range(x1.shape[3]):
          for i5 in range(x1.shape[4]):
            if x1[i1][i2][i3][i4][i5] + x2[i1][i2][i3][i4][i5] < 255:
              x1[i1][i2][i3][i4][i5] += x2[i1][i2][i3][i4][i5]
  
  return x1

**Add the video sets**

In [21]:
vid_add = addVideos(vidset1,vidset2)

<ipython-input-20-b040a19473e1>:9: RuntimeWarning: overflow encountered in ubyte_scalars
  if x1[i1][i2][i3][i4][i5] + x2[i1][i2][i3][i4][i5] < 255:
<ipython-input-20-b040a19473e1>:10: RuntimeWarning: overflow encountered in ubyte_scalars
  x1[i1][i2][i3][i4][i5] += x2[i1][i2][i3][i4][i5]


In [22]:
vid_add.shape

(2, 10, 300, 300, 3)

In [23]:
from google.colab.patches import cv2_imshow

for i in vid_add:
  j=0
  for j in range(10):
    cv2_imshow(i[j])
    if cv2.waitKey(25) & 0xFF==ord('q'):
      break
    
  cap.release()
  cv2.destroyAllWindows()

Output hidden; open in https://colab.research.google.com to view.

**Subtract the video sets**

In [24]:
vid_sub = subtractVideos(vidset1,vidset2)

In [25]:
vid_sub.shape

(2, 10, 300, 300, 3)

In [26]:
from google.colab.patches import cv2_imshow

for i in vid_sub:
  j=0
  for j in range(10):
    cv2_imshow(i[j])
    if cv2.waitKey(25) & 0xFF==ord('q'):
      break
    
  cap.release()
  cv2.destroyAllWindows()

Output hidden; open in https://colab.research.google.com to view.

# **Perceptron network for simple adder circuit**

In [27]:
def thres(x):
  if x > 0:
    return 1
  else:
    return 0

def perceptronModel(x, w, b):
  y = np.dot(w,x)
  y = y + b
  y = thres(y)
  return y

def nand(x):
  w = np.array([-3,-2])
  b = 4
  return perceptronModel(x,w,b)

def xor(x):
  return nand([nand([x[0], nand(x)]), nand([nand(x),x[1]])])

def And(x):
  return nand([nand(x), nand(x)])

def adder(x):
  return [xor(x), And(x)]  

In [28]:
print("Addition of 0 and 0 gives: ", adder([0,0])[0], ", carry is:", adder([0, 0])[1])
print("Addition of 0 and 1 gives: ", adder([0,1])[0], ", carry is:", adder([0, 1])[1])
print("Addition of 1 and 0 gives: ", adder([1,0])[0], ", carry is:", adder([1, 0])[1])
print("Addition of 1 and 1 gives: ", adder([1,1])[0], ", carry is:", adder([1, 1])[1])

Addition of 0 and 0 gives:  0 , carry is: 0
Addition of 0 and 1 gives:  1 , carry is: 0
Addition of 1 and 0 gives:  1 , carry is: 0
Addition of 1 and 1 gives:  0 , carry is: 1
